### NumPy Introduction

**NumPy(Numerical Python)** is a fundamental library for Python numerical computing. It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.
 - Installing & Importing NumPy
 - Creating NumPy Arrays
 - Array Creation Methods
 - Array Indexing and Slicing
 - Array Operations
 - Mathematical Functions
 - Reshaping & Flattening
 - Stacking & Concatenation
 - Linear Algebra Operations
 - Random Number Generation

### Installing & Importing NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

### Creating NumPy Arrays

 - **Using ndarray** : The array object is called ndarray. NumPy arrays are created using the array() function.

In [3]:
import numpy as np

# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Creation Methods

NumPy provides functions to create arrays with specific values or shapes, like zeros, ones, random numbers, or ranges.

In [4]:
import numpy as np

# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)

# Array of ones
ones = np.ones((3, 2))
print(ones)

# Random array
rand = np.random.rand(2, 2)  # Uniform distribution [0, 1)
print(rand)

# Range of values
arange = np.arange(0, 10, 2)  # Start, stop, step
print(arange)  

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.75255514 0.30674186]
 [0.52739314 0.44799735]]
[0 2 4 6 8]


### Array Indexing and Slicing

 - **Basic Indexing** : Basic indexing in NumPy allows you to access elements of an array using indices.

In [5]:
import numpy as np

# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])  

# Negative indexing
print("Negative indexing:", arr1d[-1])  

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0]) 

Single element access: 30
Negative indexing: 50
Multidimensional array access: 4


 - **Slicing** : Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [6]:
import numpy as np

arr = np.array([0, 10, 20, 30, 40, 50])

print("Range of Elements:",arr[1:4]) # index 1 to 4
print("Range of Elements:",arr[:3])  # first 3 elements
print("Range of Elements:",arr[-3:]) # last 3 elements

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
#all rows, second column
print("Multidimensional Slicing:", arr1[:, 1])

Range of Elements: [10 20 30]
Range of Elements: [ 0 10 20]
Range of Elements: [30 40 50]
Multidimensional Slicing: [2 5]


 - **Advanced Indexing** : Advanced Indexing in NumPy provides more powerful and flexible ways to access and manipulate array elements.

In [7]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing 
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing 
cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


### Array Operations

Element-wise operations in NumPy allow you to perform mathematical operations on each element of an array individually, without the need for explicit loops.

 - **Element-wise Operations** : We can perform arithmetic operations like addition, subtraction, multiplication, and division directly on NumPy arrays.

In [8]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y  
print("Addition:",add)

# Subtraction
subtract = x - y 
print("substration:",subtract)

# Multiplication
multiply = x * y 
print("multiplication:",multiply)

# Division
divide = x / y  
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


 - **Unary Operation** : These operations are applied to each individual element in the array, without the need for multiple arrays (as in binary operations).

In [9]:
import numpy as np

# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(arr)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]


 - **Binary Operators** : Numpy Binary Operations apply to the array elementwise and a new array is created. We can use all basic arithmetic operators like +, -, /,  etc. In the case of +=, -=, = operators, the existing array is modified.

In [10]:
import numpy as np

# Creating an array
arr = np.array([10, 20, 30, 40])

# Binary operations (element-wise)
print("Addition:", arr + 5)  
print("Subtraction:", arr - 5) 
print("Multiplication:", arr * 2) 
print("Division:", arr / 2)   
print("Floor Division:", arr // 3) 
print("Modulus:", arr % 7)   
print("Exponentiation:", arr ** 2) 

# In-place operations (modifies the original array)
arr += 5  
print("After += 5:", arr) 

arr -= 5  
print("After -= 5:", arr)  


Addition: [15 25 35 45]
Subtraction: [ 5 15 25 35]
Multiplication: [20 40 60 80]
Division: [ 5. 10. 15. 20.]
Floor Division: [ 3  6 10 13]
Modulus: [3 6 2 5]
Exponentiation: [ 100  400  900 1600]
After += 5: [15 25 35 45]
After -= 5: [10 20 30 40]


### Mathematical Functions

NumPy offers functions like sum, mean, standard deviation, dot product , Sin, Cos, exp, etc...


In [11]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Aggregation functions
print("Sum:", np.sum(arr))  
print("Mean:", np.mean(arr))  
print("Standard Deviation:", np.std(arr))  
print("Variance:", np.var(arr))  

# Trigonometric functions
angles = np.array([0, 30, 45, 60, 90]) 
radians = np.radians(angles)  
print("Sine values:", np.sin(radians))
print("Cosine values:", np.cos(radians))

# Exponential & Logarithmic functions
print("Exponential:", np.exp(arr)) 
print("Natural Log (ln):", np.log(arr))  
print("Log base 10:", np.log10(arr))  

# Dot product (Linear Algebra)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Dot Product:", np.dot(A, B))  

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Log (ln): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Dot Product: 32


### Reshaping & Flattening

Change the shape of an array (reshape) or swap axes (transpose) to fit ML model requirements.

In [12]:
import numpy as np

# Original array (2D)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n", arr)

# Reshaping (Changing shape from (2,3) to (3,2))
reshaped = arr.reshape(3, 2)
print("\nReshaped (3x2):\n", reshaped)

# Flattening the array (converting to 1D)
flattened = arr.flatten()  
print("\nFlattened Array:", flattened)

# Using ravel() (returns a view, changes will affect original)
raveled = arr.ravel()
print("\nRaveled Array:", raveled)

# Modifying raveled array (affects original)
raveled[0] = 99
print("\nModified Raveled Array:", raveled)
print("Original Array After ravel() Modification:\n", arr)

Original Array:
 [[1 2 3]
 [4 5 6]]

Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Flattened Array: [1 2 3 4 5 6]

Raveled Array: [1 2 3 4 5 6]

Modified Raveled Array: [99  2  3  4  5  6]
Original Array After ravel() Modification:
 [[99  2  3]
 [ 4  5  6]]


### Stacking & Concatenation

In Machine Learning (ML) and Data Science, combining arrays is essential for data manipulation. NumPy provides powerful functions for stacking and concatenation.

In [13]:
import numpy as np

# Creating sample arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Array A:\n", A)
print("\nArray B:\n", B)

# Concatenation (Merging along existing axes)
concat_0 = np.concatenate((A, B), axis=0)  # Row-wise
concat_1 = np.concatenate((A, B), axis=1)  # Column-wise

print("\nConcatenation (Row-wise, axis=0):\n", concat_0)
print("\nConcatenation (Column-wise, axis=1):\n", concat_1)

# Stacking (Creates a new dimension)
stack_0 = np.stack((A, B), axis=0)  # New axis at 0
stack_1 = np.stack((A, B), axis=1)  # New axis at 1

print("\nStacking Along New Axis (axis=0):\n", stack_0)
print("\nStacking Along New Axis (axis=1):\n", stack_1)

# Horizontal and Vertical Stacking
h_stacked = np.hstack((A, B))  # Horizontal Stacking
v_stacked = np.vstack((A, B))  # Vertical Stacking
d_stacked = np.dstack((A, B))  # Depth Stacking

print("\nHorizontally Stacked:\n", h_stacked)
print("\nVertically Stacked:\n", v_stacked)
print("\nDepth Stacked:\n", d_stacked)

Array A:
 [[1 2]
 [3 4]]

Array B:
 [[5 6]
 [7 8]]

Concatenation (Row-wise, axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenation (Column-wise, axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

Stacking Along New Axis (axis=0):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Stacking Along New Axis (axis=1):
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Depth Stacked:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### Linear Algebra Operations

NumPy Linear Algebra is a module (numpy.linalg) that provides efficient mathematical functions for performing matrix operations such as multiplication, determinant calculation, inversion, eigenvalue decomposition, solving linear equations, and singular value decomposition (SVD)

In [14]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([5, 11])  # Constants for equation Ax = B

# Matrix Multiplication
dot_product = np.dot(A, B)
matmul_product = np.matmul(A, B)

# Determinant
det_A = np.linalg.det(A)

# Inverse
inverse_A = np.linalg.inv(A)

# Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Solving Linear Equations Ax = B
solution = np.linalg.solve(A, C)

# Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(A)

# Print Outputs
print("Matrix Multiplication (Dot Product):\n", dot_product)
print("\nMatrix Multiplication (Matmul):\n", matmul_product)
print("\nDeterminant of A:", det_A)
print("\nInverse of A:\n", inverse_A)
print("\nEigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)
print("\nSolution for Ax = B:\n", solution)
print("\nSingular Value Decomposition (SVD):\nU:\n", U, "\nS:\n", S, "\nV:\n", V)

Matrix Multiplication (Dot Product):
 [[19 22]
 [43 50]]

Matrix Multiplication (Matmul):
 [[19 22]
 [43 50]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A:
 [-0.37228132  5.37228132]

Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Solution for Ax = B:
 [1. 2.]

Singular Value Decomposition (SVD):
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] 
S:
 [5.4649857  0.36596619] 
V:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


### Random Number Generation

Generate random numbers for initializing weights, shuffling data, or creating synthetic datasets.

NumPy Random Number Generation (numpy.random) is a module that provides functions to generate random numbers, including integers, floats, normal distributions, and permutations.

In [15]:
import numpy as np

# 1. Generate random integer and float
rand_int = np.random.randint(10, 50)
rand_float = np.random.rand()

# 2. Generate random arrays
rand_array = np.random.rand(5)  # 1D array of 5 floats
rand_matrix = np.random.randint(1, 100, (3, 3))  # 3x3 integer matrix

# 3. Random choice
arr = np.array([10, 20, 30, 40, 50])
random_choice = np.random.choice(arr)

# 4. Normal Distribution
normal_dist = np.random.normal(0, 1, 5)

# 5. Shuffling & Permutation
shuffle_arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(shuffle_arr)  # In-place shuffle
perm_arr = np.random.permutation(shuffle_arr)  # New permutation

# Print Outputs
print("Random Integer:", rand_int)
print("Random Float:", rand_float)
print("\n1D Array of Random Floats:\n", rand_array)
print("\n2D Random Integer Matrix:\n", rand_matrix)
print("\nRandom Choice from Array:", random_choice)
print("\nRandom Numbers from Normal Distribution:\n", normal_dist)
print("\nShuffled Array:\n", shuffle_arr)
print("\nRandomly Permuted Array:\n", perm_arr)

Random Integer: 48
Random Float: 0.23893824785857642

1D Array of Random Floats:
 [0.42967035 0.52821535 0.11450325 0.9110085  0.53383167]

2D Random Integer Matrix:
 [[ 9 31 29]
 [ 9 45 42]
 [ 5 44 69]]

Random Choice from Array: 50

Random Numbers from Normal Distribution:
 [ 0.05662966 -0.3295585  -0.01738985 -1.10986416 -1.13844562]

Shuffled Array:
 [2 1 4 3 5]

Randomly Permuted Array:
 [5 2 4 3 1]
